server:
  port: 8080
datasource:
  info:
    username: postgres
    password: TJvZXAQfdsZyF4xaaKDBKGVR9k3aUpqQzF
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    r2dbc-url: r2dbc:pool:postgresql://localhost:5432/postgres
    driver: org.postgresql.Driver
    flyway-location: classpath:db/migration

spring:
  r2dbc:
    url: ${datasource.info.r2dbc-url}
    username: ${datasource.info.username}
    password: ${datasource.info.password}
  datasource:
    username: ${datasource.info.username}
    password: ${datasource.info.password}
    driver-class-name: ${datasource.info.driver}
  flyway:
    url: ${datasource.info.jdbc-url}
    locations: ${datasource.info.flyway-location}
    user: ${datasource.info.username}
    password: ${datasource.info.password}
    out-of-order: true
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      key-length: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: owner

